config/routes.rb
Codechallenge::Application.routes.draw do
  resources :multiple_choice_answers

  resources :free_response_answers

  resources :multiple_choice_questions

  resources :free_response_questions

  resources :admin, only: [:index] 
  resources :quizzes

  devise_for :users

  resources :users do 
    member do
      get 'get_quiz'
      get 'start_new_quiz'
    end
  end

  root to: "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name
  attr_accessible :last_name, :school, :year_in_school, :major
  # attr_accessible :title, :body

  has_many :quizzes
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @quiz =  @user.quizzes.last
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end


  def generate_new_quiz(category)
    quiz = Quiz.new(params[:quiz])
    quiz.in_progress = true
    quiz.category = category
    quiz.user_id = current_user.id
    i = 0
    length = MultipleChoiceQuestion.all.length
    while i < 12 && i < length 
      while true
        mc_question = MultipleChoiceQuestion.all.sample
        if !quiz.mc_questions.include? mc_question
          quiz.mc_questions << mc_question
          break
        end
      end
      i = i + 1
    end

    i = 0
    length = FreeResponseQuestion.all.length
    while i < 3 && i < length 
      while true
        fr_question = FreeResponseQuestion.all.sample
        if !quiz.fr_questions.include? fr_question
          quiz.fr_questions << fr_question
          break
        end
      end
      i = i + 1
    end


    quiz.save!
    return quiz
  end

  def start_new_quiz 
    @user = current_user
    category = params[:category]
    @quiz = generate_new_quiz(category)
    respond_to do |format|
      format.html 
      format.js   
    end
  end


  def get_quiz
    @user = current_user
    category = params[:category]

    temp_quiz = @user.quizzes.where(:category => category, :is_completed => false, :in_progress => true).first
    if temp_quiz
      @quiz = temp_quiz
      @existing_quiz = true
    else
      @category = category
      @existing_quiz = false
    end

    respond_to do |format|
      format.html 
      format.js   
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_profile_form.html.erb
<div class="square span12" id="edit-user-form-square" style="display:none">
	<div id="edit-user-form" style="display:none">
		<%= simple_form_for(user) do |f| %>
		<%= f.error_notification %>

		<div class="form-inputs">
			<%= f.input :first_name %>
			<%= f.input :last_name %>
			<%= f.input :school %>
			<%= f.input :year_in_school %>
			<%= f.input :major %>
		</div>
		<%= f.button :submit %>
		<% end %>
	</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_new_quiz.html.erb
<div class="square span18 offset3" id="take-new-quiz" style="display:none">
		<div class="row">
			<div class="span17">
				<h1>You are about to take a new <%= category%> quiz! </h1>
				<hr/>
			</div>
		</div>
	<div class="row" style="margin-top: 20px">
		<div class="t-center">
			<%= link_to "Begin the quiz!", start_new_quiz_user_path(:category => category), remote: true, id: "begin-new-quiz-btn", class: "btn btn-large btn-danger take-new-quiz-btn"%>
		</div>
	</div>
</div>

app/views/users/_pick_quiz_category.html.erb
<div class="square span6" id="pick-quiz-category" style="display:none">
	<div id="quiz-categories" style="display:none">
		<hr style="margin-top:15px"/>
		<% quiz_categories.each do |category| %>

		<%= link_to(get_quiz_user_path(:category => category), remote: true, style: "color:white") do %>
			<div class="row control-panel new_quiz_cat" id="take_new_quiz_btn">
				<div class="span6"> <%= category %> </div>
			</div>
		<% end %>
		<hr/>
		<% end %>
	</div>
</div>

app/views/users/_take_quiz_portal.html.erb
<div class="square span18 offset3" id="take-quiz-portal" style="display:none;">
	<div class="row">
		<div class="span17">
			<h1 id="quiz-heading">You are now taking a <%= quiz.category%> quiz! </h1>
			<hr/>
		</div>
	</div>
	<div class="row">
		<div class="span18" id="questions-paragraph">
			<% quiz.mc_questions.each do |mc_question| %>
			<%= render partial: "multiple_choice_questions/show_mc_question", locals: {user: user, mc_question: mc_question, possible_answers: shuffle_answers(mc_question) } %>
			<% end %>
			<% quiz.fr_questions.each do |free_response_question| %>
			<%= render partial: "free_response_questions/show_question", locals: {user: user, free_response_question: free_response_question } %> 

			<% end %>

		</div>
	</div>
	<div class="row" id="quiz-completed-btn" style="margin-top: 20px">
		<div class="t-center">
			<%= link_to "I am done!", nil, class: "btn btn-large btn-danger", style: "color:white; width:200px"%>
		</div>
	</div>
	<div class="row" id="start-new-quiz-btn" style="margin-top:10px; display:none">
		<div class="t-center">
			<%= link_to "I am done!", nil, class: "btn btn-large btn-danger", style: "color:white; width:200px"%>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<img src='/assets/modernoffice.jpg' class="bg">

<div class="" style="margin-top:100px;">
	<div class="row" >
		<div class="square span6" id="control-panel" style="display:">
			<hr style="margin-top:15px"/>
			<%= link_to("#take-quiz") do %>
			<div class="row control-panel" id="take-quiz-btn">
				<div class="span6">Take a Code Quiz</div>
			</div>
			<% end %>
			<hr/>

			<div class="row control-panel" id="view-results-btn">
				<div class="span6" id="view-past-results-btn">View Past Results</div>
			</div>
			<hr/>
			<div class="row control-panel" id="edit-profile-btn" >
				<div class="span6">Edit Your Profile</div>
			</div>
			<hr/>
		</div>
		<%= render partial: "edit_profile_form", locals: {user: @user} %>
		<%= render partial: "pick_quiz_category", locals: {user: @user} %>
		
	</div>
</div>

<div id="take-quiz-container" style="margin-top:-50px">
</div>