config/routes.rb
Codechallenge::Application.routes.draw do
  resources :multiple_choice_answers

  resources :free_response_answers

  resources :multiple_choice_questions

  resources :free_response_questions

  resources :admin, only: [:index] 
  resources :quizzes

  devise_for :users

  resources :users do 
    member do
      get 'get_quiz'
      get 'start_new_quiz'
    end
  end

  root to: "home#index"

end

app/models/multiple_choice_question.rb
class MultipleChoiceQuestion < ActiveRecord::Base
  
  attr_accessible :title, :quiz_id, :prompt, :correct_answer, :wrong_answers, :category
  belongs_to :quiz

end

app/controllers/multiple_choice_questions_controller.rb
class MultipleChoiceQuestionsController < ApplicationController
  # GET /multiple_choice_questions
  # GET /multiple_choice_questions.json
  def index
    @multiple_choice_questions = MultipleChoiceQuestion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @multiple_choice_questions }
    end
  end

  # GET /multiple_choice_questions/1
  # GET /multiple_choice_questions/1.json
  def show
    @multiple_choice_question = MultipleChoiceQuestion.find(params[:id])
    @possible_answers = []
    @multiple_choice_question.wrong_answers.split(",").each do |wrong_answer|
      @possible_answers << wrong_answer
    end
    @possible_answers << @multiple_choice_question.correct_answer
    @possible_answers.shuffle!
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @multiple_choice_question }
    end
  end

  # GET /multiple_choice_questions/new
  # GET /multiple_choice_questions/new.json
  def new
    @multiple_choice_question = MultipleChoiceQuestion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @multiple_choice_question }
    end
  end

  # GET /multiple_choice_questions/1/edit
  def edit
    @multiple_choice_question = MultipleChoiceQuestion.find(params[:id])
  end

  # POST /multiple_choice_questions
  # POST /multiple_choice_questions.json
  def create
    @multiple_choice_question = MultipleChoiceQuestion.new(params[:multiple_choice_question])

    respond_to do |format|
      if @multiple_choice_question.save
        format.html { redirect_to @multiple_choice_question, notice: 'Multiple choice question was successfully created.' }
        format.json { render json: @multiple_choice_question, status: :created, location: @multiple_choice_question }
      else
        format.html { render action: "new" }
        format.json { render json: @multiple_choice_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /multiple_choice_questions/1
  # PUT /multiple_choice_questions/1.json
  def update
    @multiple_choice_question = MultipleChoiceQuestion.find(params[:id])

    respond_to do |format|
      if @multiple_choice_question.update_attributes(params[:multiple_choice_question])
        format.html { redirect_to @multiple_choice_question, notice: 'Multiple choice question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @multiple_choice_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /multiple_choice_questions/1
  # DELETE /multiple_choice_questions/1.json
  def destroy
    @multiple_choice_question = MultipleChoiceQuestion.find(params[:id])
    @multiple_choice_question.destroy

    respond_to do |format|
      format.html { redirect_to multiple_choice_questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/multiple_choice_questions_helper.rb
module MultipleChoiceQuestionsHelper
end

app/views/multiple_choice_questions/_form.html.erb
<%= simple_form_for(@multiple_choice_question) do |f| %>

<div class="form-inputs">
	<%= f.input :title %>
	<%= f.input :prompt, input_html: {:style => "height: 200px"} %>
	<%= f.input :correct_answer %>
	<%= f.input :wrong_answers, hint: "separate wrong answers with commas" %>
	<%= f.input :category, :collection => mc_categories %>
</div>

<div class="form-actions">
	<%= f.button :submit %>
</div>
<% end %>

app/views/multiple_choice_questions/_show_mc_question.html.erb
<div class="row">
	<div class="span16">
		<b><%= mc_question.title %></b>
	</div>
</div>
<div class="row">
	<div class="span16">
		<%= mc_question.prompt %>
	</div>
</div>
<div class="row">
	<div class="span16">
		<% possible_answers.each do |answer| %>
		<span style="margin-right:10px">
			<%= radio_button "question", mc_question.id, answer, style: "margin-top:-5px" %>
			<%= answer %>
		</span>
		<% end %>
	</div>
</div>

app/views/multiple_choice_questions/edit.html.erb
<h1>Editing multiple_choice_question</h1>

<%= render 'form' %>

<%= link_to 'Show', @multiple_choice_question %> |
<%= link_to 'Back', multiple_choice_questions_path %>

app/views/multiple_choice_questions/index.html.erb
<h1>Listing multiple_choice_questions</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @multiple_choice_questions.each do |multiple_choice_question| %>
  <tr>
    <td><%= link_to 'Show', multiple_choice_question %></td>
    <td><%= link_to 'Edit', edit_multiple_choice_question_path(multiple_choice_question) %></td>
    <td><%= link_to 'Destroy', multiple_choice_question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Multiple choice question', new_multiple_choice_question_path %>

app/views/multiple_choice_questions/new.html.erb
<h1>New multiple_choice_question</h1>

<%= render 'form' %>

<%= link_to 'Back', multiple_choice_questions_path %>

app/views/multiple_choice_questions/show.html.erb
<div class="row">
	<div class="span16">
		<b><%= @multiple_choice_question.title %></b>
	</div>
</div>
<div class="row">
	<div class="span16">
		<%= @multiple_choice_question.prompt %>
	</div>
</div>
<div class="row">
	<div class="span16">
		<% @possible_answers.each do |answer| %>
		<span style="margin-right:10px">
			<%= radio_button "question", @multiple_choice_question.id, answer, style: "margin-top:-5px" %>
			<%= answer %>
		</span>
		<% end %>
	</div>
</div>

<%= link_to 'Edit', edit_multiple_choice_question_path(@multiple_choice_question) %> 