config/routes.rb
Codechallenge::Application.routes.draw do
  resources :multiple_choice_answers

  resources :free_response_answers

  resources :multiple_choice_questions

  resources :free_response_questions

  resources :admin, only: [:index] 
  resources :quizzes

  devise_for :users

  resources :users do 
    member do
      get 'get_quiz'
      get 'start_new_quiz'
    end
  end

  root to: "home#index"

end

app/models/free_response_question.rb
class FreeResponseQuestion < ActiveRecord::Base
  
  attr_accessible :title, :quiz_id, :prompt, :instructions, :correct_answer, :category

  belongs_to :quiz
end

app/controllers/free_response_questions_controller.rb
class FreeResponseQuestionsController < ApplicationController
  # GET /free_response_questions
  # GET /free_response_questions.json
  def index
    @free_response_questions = FreeResponseQuestion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @free_response_questions }
    end
  end

  # GET /free_response_questions/1
  # GET /free_response_questions/1.json
  def show
    @free_response_question = FreeResponseQuestion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @free_response_question }
    end
  end

  # GET /free_response_questions/new
  # GET /free_response_questions/new.json
  def new
    @free_response_question = FreeResponseQuestion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @free_response_question }
    end
  end

  # GET /free_response_questions/1/edit
  def edit
    @free_response_question = FreeResponseQuestion.find(params[:id])
  end

  # POST /free_response_questions
  # POST /free_response_questions.json
  def create
    @free_response_question = FreeResponseQuestion.new(params[:free_response_question])

    respond_to do |format|
      if @free_response_question.save
        format.html { redirect_to @free_response_question, notice: 'Free response question was successfully created.' }
        format.json { render json: @free_response_question, status: :created, location: @free_response_question }
      else
        format.html { render action: "new" }
        format.json { render json: @free_response_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /free_response_questions/1
  # PUT /free_response_questions/1.json
  def update
    @free_response_question = FreeResponseQuestion.find(params[:id])

    respond_to do |format|
      if @free_response_question.update_attributes(params[:free_response_question])
        format.html { redirect_to @free_response_question, notice: 'Free response question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @free_response_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /free_response_questions/1
  # DELETE /free_response_questions/1.json
  def destroy
    @free_response_question = FreeResponseQuestion.find(params[:id])
    @free_response_question.destroy

    respond_to do |format|
      format.html { redirect_to free_response_questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/free_response_questions_helper.rb
module FreeResponseQuestionsHelper
end

app/views/free_response_questions/_form.html.erb
<%= simple_form_for(@free_response_question) do |f| %>

<div class="form-inputs">
  <%= f.input :title %>
  <%= f.input :prompt, input_html: {:style => "height: 200px"} %>
  <%= f.input :instructions, input_html: {:style => "height: 200px"} %>
  <%= f.input :category, :collection => mc_categories %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/free_response_questions/_show_question.html.erb
<div class="row">
	<div class="span12">
		<b><%= free_response_question.title %></b>
	</div>
</div>
<div class="row">
	<div class="span12">
		<%= free_response_question.prompt %>
	</div>
</div>

<div class="row" style="margin-top:5px">
	<div class="span17">
		<div id="instructions" style="display:none"> <%=free_response_question.instructions%> </div>

		<div id="editor"></div>
	</div>
</div>

<script> 
editor = ace.edit("editor");
editor.insert("/** \n" + " *" + $("#instructions").text() + "\n" + "**/\n\n");
</script>

app/views/free_response_questions/edit.html.erb
<h1>Editing free_response_question</h1>

<%= render 'form' %>

<%= link_to 'Show', @free_response_question %> |
<%= link_to 'Back', free_response_questions_path %>

app/views/free_response_questions/index.html.erb
<h1>Listing free_response_questions</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @free_response_questions.each do |free_response_question| %>
  <tr>
    <td><%= link_to 'Show', free_response_question %></td>
    <td><%= link_to 'Edit', edit_free_response_question_path(free_response_question) %></td>
    <td><%= link_to 'Destroy', free_response_question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Free response question', new_free_response_question_path %>

app/views/free_response_questions/new.html.erb
<h1>New free_response</h1>

<%= render 'form' %>

<%= link_to 'Back', free_responses_path %>

app/views/free_response_questions/show.html.erb
<div class="row" style="margin-top:100px">
	<div class="span12">
		<b><%= @free_response_question.title %></b>
	</div>
</div>
<div class="row">
	<div class="span12">
		<%= @free_response_question.prompt %>
	</div>
</div>
<div class="row">
	<div class="span12">
		<%= @free_response_question.instructions %>
	</div>
</div>
<div class="row" style="margin-top:5px">
	<div class="span12">
		
	</div>
</div>

<div id="instructions" style="display:none"> <%=@free_response_question.instructions%> </div>

<div id="editor"></div>

<script> 
	editor = ace.edit("editor");
 	editor.insert("/** \n" + " *" + $("#instructions").text() + "\n" + "**/\n\n");
</script>


<%= link_to 'Edit', edit_free_response_path(@free_response_question) %> 