config/routes.rb
Codechallenge::Application.routes.draw do
  resources :multiple_choice_answers

  resources :free_response_answers

  resources :multiple_choice_questions

  resources :free_response_questions

  resources :admin, only: [:index] 
  resources :quizzes

  devise_for :users

  resources :users do 
    member do
      get 'get_quiz'
      get 'start_new_quiz'
    end
  end

  root to: "home#index"

end

app/models/free_response_answer.rb
class FreeResponseAnswer < ActiveRecord::Base
  
  attr_accessible :quiz_id, :user_response, :points_scored, :free_response_question_id

  belongs_to :quiz
end

app/controllers/free_response_answers_controller.rb
class FreeResponseAnswersController < ApplicationController
  # GET /free_response_answers
  # GET /free_response_answers.json
  def index
    @free_response_answers = FreeResponseAnswer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @free_response_answers }
    end
  end

  # GET /free_response_answers/1
  # GET /free_response_answers/1.json
  def show
    @free_response_answer = FreeResponseAnswer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @free_response_answer }
    end
  end

  # GET /free_response_answers/new
  # GET /free_response_answers/new.json
  def new
    @free_response_answer = FreeResponseAnswer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @free_response_answer }
    end
  end

  # GET /free_response_answers/1/edit
  def edit
    @free_response_answer = FreeResponseAnswer.find(params[:id])
  end

  # POST /free_response_answers
  # POST /free_response_answers.json
  def create
    @free_response_answer = FreeResponseAnswer.new(params[:free_response_answer])

    respond_to do |format|
      if @free_response_answer.save
        format.html { redirect_to @free_response_answer, notice: 'Free response answer was successfully created.' }
        format.json { render json: @free_response_answer, status: :created, location: @free_response_answer }
      else
        format.html { render action: "new" }
        format.json { render json: @free_response_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /free_response_answers/1
  # PUT /free_response_answers/1.json
  def update
    @free_response_answer = FreeResponseAnswer.find(params[:id])

    respond_to do |format|
      if @free_response_answer.update_attributes(params[:free_response_answer])
        format.html { redirect_to @free_response_answer, notice: 'Free response answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @free_response_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /free_response_answers/1
  # DELETE /free_response_answers/1.json
  def destroy
    @free_response_answer = FreeResponseAnswer.find(params[:id])
    @free_response_answer.destroy

    respond_to do |format|
      format.html { redirect_to free_response_answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/free_response_answers_helper.rb
module FreeResponseAnswersHelper
end

app/views/free_response_answers/_form.html.erb
<%= simple_form_for(@free_response_answer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/free_response_answers/edit.html.erb
<h1>Editing free_response_answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @free_response_answer %> |
<%= link_to 'Back', free_response_answers_path %>

app/views/free_response_answers/index.html.erb
<h1>Listing free_response_answers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @free_response_answers.each do |free_response_answer| %>
  <tr>
    <td><%= link_to 'Show', free_response_answer %></td>
    <td><%= link_to 'Edit', edit_free_response_answer_path(free_response_answer) %></td>
    <td><%= link_to 'Destroy', free_response_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Free response answer', new_free_response_answer_path %>

app/views/free_response_answers/new.html.erb
<h1>New free_response_answer</h1>

<%= render 'form' %>

<%= link_to 'Back', free_response_answers_path %>

app/views/free_response_answers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_free_response_answer_path(@free_response_answer) %> |
<%= link_to 'Back', free_response_answers_path %>